name: Workflow

on:
  push:
    # branches: [ "master" ]
    branches: "*"
  pull_request:
    branches: "*"

env:
  DOC_DIR: build/dokka/html/

jobs:
  publish_templates:
    name: Push the latest versions of the templates to GCS
    timeout-minutes: 5
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        name: 'Authenticate to Google Cloud'
        with:
          workload_identity_provider: 'projects/205017367875/locations/global/workloadIdentityPools/github-ci/providers/dataflow-templates-ci'
          service_account: 'dataflow-template-github-ci@whylogs-359820.iam.gserviceaccount.com'




